473 search decrease popularity relevance
inventaire/inventaire pull request #478
Opened 2021-01-03 18:10 UTC by jum-s

fix #473 

tested with queries
"Jean baudrillard"
"Victor Hugo"
"Alexandre Dumas"
"Victor mees"
"Sanjay Gandhi"
on "All", "Author" and "Work"

one may see the score results by adding a function to `server/controllers/search/lib/type_search.js#L43` such as: 
```js
  .then(foo => {
    const bar = foo.hits.hits.map(f => {
      return {
        score: f._score,
        label: f._source.labels.en || f._source.labels.fr || 'foo',
        id: f._id
      }
    })
    console.log('result', bar)
    return foo
  })
```

2021-01-10 16:07 UTC, maxlath requested changes
It does seem to work much better for lonely exact matches without exact homonyms (ex: "Jean Baudrillard") but seems to break popularity sorting when there are exact homonyms (ex: "Victor Hugo", "Stephan King"). Removing the `boost: 5` seems to work better in that regard

2021-01-10 16:07 UTC, maxlath commented on server/controllers/search/lib/entities_query_builder.js
> +        boost: 5,
```suggestion
```

2021-01-11 13:03 UTC, jum-s commented
"Stephan King" does not bring up the famous author... "Stephen King" does. popularity really got smashed but i think we can try like that and adjust again in the future

2021-01-11 15:44 UTC, maxlath commented
merging this, as it already is an improvement, but I would let the issue open as we can probably do better. Also, I get some red tests in `tests/api/search/entities.test.js`, due to local entities with exact matches still being smashed by Wikidata entities with partial matches

2021-01-11 15:44 UTC, merged