Activity pub shelf
inventaire/inventaire pull request #553
Opened 2021-09-26 20:24 UTC by jum-s

shelf as actors 
- actor name is `shelf:shelfId`, 
  - prefix `shelf` is welcome to stay in order to disambiguate outbox and follow from the controller (without requesting db doc)
  - `:` needs some occasional `decodeURIComponent` maybe a `-` is more straightforward ?
- implements `outbox` and `follow`
- creates activity on `addItems` only

ways of improvements: 
- create activity on other events : such as `item:udpate:listing` `private -> public`
- dereference activity on `removeItems`
- avec a more reable sluggish actor name (ie. `stableUsername:shelf:stableShefName)

2021-09-27 16:38 UTC, maxlath commented
misses webfinger implementation and tests, which should probably be done after a rebase on the new `activity-pub-entities` tip, see  https://github.com/inventaire/inventaire/pull/552#issuecomment-928019534

2021-09-27 16:57 UTC, jum-s commented
done with 5662357

2021-09-27 21:32 UTC, maxlath requested changes

2021-09-27 21:34 UTC, jum-s commented on server/controllers/activitypub/lib/format_items_activities.js
> +      until: _.max(_.map(activitiesDocs, 'object.items.until'))
i unsucessfully tried this and finally dropped it

2021-09-27 21:47 UTC, jum-s commented on server/controllers/activitypub/lib/radio_hooks.js
> +  deliverEntityActivitiesFromPatch(patch)
solved 4f7e0508

2021-09-27 21:47 UTC, jum-s commented on server/controllers/activitypub/lib/radio_hooks.js
> +    Promise.all(shelvesIds.map(debounceActivities))
solved 4f7e0508

2021-09-27 21:47 UTC, jum-s commented on server/controllers/shelves/lib/shelves.js
> +    emit('shelves:update', ids)
solved 4f7e0508

2021-09-27 21:48 UTC, jum-s commented on server/controllers/activitypub/lib/radio_hooks.js
> +  radio.on('patch:created', _deliverEntityActivitiesFromPatch)
i dont, this is simply where all the hooks are, im fine leaving it here for now
Is this blocking ? i would like to merge this quickly for the moment

2021-09-27 21:49 UTC, jum-s commented on server/controllers/activitypub/lib/format_items_activities.js
> +    const publicRangeItems = allActivitiesItems.filter(itemsWithinActivityRange(since, until))
left it like that for now but added a comment in 4f7e0508

2021-09-27 22:07 UTC, maxlath commented on server/controllers/activitypub/lib/radio_hooks.js
> +  radio.on('patch:created', _deliverEntityActivitiesFromPatch)
If speed is a problem, I can quickly split it :p I won't block on this, but it's not some trivial one liner functions that we are stacking in this file. While complex `deliverEntityActivitiesFromPatch` and its dependencies could be in a nicely isolated module, and instead here we have to scroll though the file to understand what's happening, for 0 added value

2021-09-27 22:50 UTC, jum-s commented on server/controllers/activitypub/lib/radio_hooks.js
> +  radio.on('patch:created', _deliverEntityActivitiesFromPatch)
done in db19a0dd

2021-09-28 10:37 UTC, maxlath approved these changes

2021-09-28 10:38 UTC, merged