add OpenLibrary data seed
inventaire/inventaire pull request #598
Opened 2022-01-17 11:11 UTC by maxlath

2022-01-28 18:50 UTC, jum-s commented on tests/integration/data/get_openlibrary_entry_from_isbn.test.js
> +  })
all those tests are red for me
`TypeError: data.key.split(...).at is not a function`

2022-01-28 18:51 UTC, jum-s requested changes
even though node 16 should accept `.at` i still have a ` TypeError: data.key.split(...).at is not a function` on all the tests added in this PR.

2022-01-28 19:08 UTC, jum-s approved these changes

2022-01-28 21:55 UTC, maxlath commented
@jum-s `>= 16.6.0`? Could that be that your command to run tests (via docker?) relies on an older version of Node than the server?

2022-01-29 10:32 UTC, jum-s commented
all good

2022-01-29 16:56 UTC, merged