refresh items snapshots after new entity operations
inventaire/inventaire pull request #600
Opened 2022-01-26 18:27 UTC by maxlath

namely, `revert-edit` and `restore-version`, which were not taken into account, leading to obsolete snapshot data after those operations.

The other commits are just small cleanups while being around

2022-01-28 18:55 UTC, jum-s requested changes

2022-01-28 18:55 UTC, jum-s commented on tests/api/items/snapshot.test.js
> +    it.only('should be updated when a related local entity is restored', async () => {
```suggestion
    it('should be updated when a related local entity is restored', async () => {
```

2022-01-28 21:56 UTC, maxlath commented on tests/api/items/snapshot.test.js
> +    it.only('should be updated when a related local entity is restored', async () => {
fixed in 1056590c

2022-01-29 10:33 UTC, jum-s approved these changes

2022-01-29 16:58 UTC, merged