Implement context tailored listings
inventaire/inventaire pull request #656
Opened 2022-10-05 15:05 UTC by maxlath

Currently, the main user private listings are displayed in every contexts, which can be confusing. This PR proposes to update the former `filter` parameter used for items into a `context` parameter, that takes a visibility key, and deduces what items or listings should not be returned for a given query, even if the requesting user has access rights.

2022-10-31 13:07 UTC, jum-s requested changes
Ive a test failing:

```
  1) listings:visibility
       groups
         should not return a groups-only listing to a friend:
```
looks like listing is returned on this branch

2022-11-09 14:14 UTC, maxlath commented
@jum-s that test passes for me, could you share the generated error stack trace?

2022-12-01 08:46 UTC, jum-s commented on tests/api/items/get_by_users.test.js
> -    // to avoid giving the false impression that those are visible by other members of the group
maybe for newcomers, this comment could be of interest

2022-12-01 09:15 UTC, jum-s commented on tests/api/items/get_by_users.test.js
> -    // to avoid giving the false impression that those are visible by other members of the group
done in f126177b

2022-12-01 09:16 UTC, jum-s approved these changes

2022-12-01 09:18 UTC, merged